### PR TITLE
Simplify broadcast code generation

### LINKED ISSUE #642: Broadcast operations resulting in Scalars fail
julia> Scalar(1) .+ 1
    ERROR: BoundsError: attempt to access 0-element Array{Int64,1} at index [1]
    Stacktrace:
     [1] getindex(::Array{Int64,1}, ::Int64) at ./array.jl:729
     [2] #s162#227 at /home/eivind/.julia/dev/StaticArrays/src/broadcast.jl:118 [inlined]

### PR DESCRIPTION
**Pull request by TheBB**
This simplifies code according to a tip left in a comment, by using `CartesianIndices` instead of generating indices manually. This also fixes #642 by not trying to increment an empty index.

I broke a long line there according to personal taste, if that's okay.

### CODE REVIEW

File: src/broadcast.jl [hunk 1]
```diff
@@ -105,30 +105,13 @@ scalar_getindex(x::Tuple{<: Any}) = x[1]
...
-                    break
-                else
-                    current_ind[i] = 1
-                    current_ind[i+1] += 1
-                end
-            else
-                break
-            end
-        end
+    exprs = map(CartesianIndices(newsize)) do current_ind
```
Comment (tkoolen) [inline src/broadcast.jl]: Hmm, I don't think you can safely use closures in function generators.

Comment (TheBB) [reply src/broadcast.jl]: I've never been able to trigger an error that way, and the tests seem to agree. But I'm happy to rewrite anyway.

Comment (c42f) [reply src/broadcast.jl]: Oddly enough, it seems that you can't use closures in the generated code, not the generator itself:

```julia
julia> @generated function foo()
           :(()->1)
       end
foo (generic function with 1 method)

julia> foo()
ERROR: generated function body is not pure. this likely means it contains a closure or comprehension.
Stacktrace:
 [1] top-level scope at none:0
```

Comment (andyferris) [reply src/broadcast.jl]: That's right. The generated code goes through a restricted, "pure" version of lowering, that can't modify the type tree or method tables. A closure adds both a new type and the closure method itself. 

On the other hand, while the generator itself is considered `@pure` it can contain closures/comprehensions (since they can be desugared deterministically during initial code lowering).

AFAICT these restrictions allowed Jameson to build a sound implementation of dependency-based recompilation (OTOH it's unclear to me whether they are *necessary* to create a sound implementation of dependency-based recompilation).

Comment (c42f) [reply src/broadcast.jl]: I don't it's necessary; more viewed as a limitation of the current implementation — see https://discourse.julialang.org/t/a-method-to-remove-the-use-of-runtime-eval-and-invokelatest-as-well-as-support-closures-in-generated-functions-come-with-an-implemented-proptype/27450/2

**Comment by c42f** [comment]
I haven't looked through this in detail, but it's a lot neater, Andy has approved and the tests pass, so I merged it. Thank you @TheBB!
