### PR TITLE
Broadcasting with tuples (fixes #485)

### LINKED ISSUE #485: broadcasting of Tuples and SVectors is broken
```julia
julia> (1,2) .+ [1,2]
2-element Array{Int64,1}:
 2
 4

julia> (1,2) .+ SVector(1,2) # I expected SVector(2,4)
ERROR: MethodError: no method matching +(::Tuple{Int64,Int64}, ::Int64)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:502
  +(::Complex{Bool}, ::Real) at complex.jl:292
  +(::Missing, ::Number) at missing.jl:93
  ...
Stacktrace:
 [1] macro expansion at /Users/sheehanolver/.julia/packages/StaticArrays/Ze5H3/src/broadcast.jl:133 [inlined]
 [2] _broadcast at /Users/sheehanolver/.julia/packages/StaticArrays/Ze5H3/src/broadcast.jl:94 [inlined]
 [3] copy at /Users/sheehanolver/.julia/packages/StaticArrays/Ze5H3/src/broadcast.jl:24 [inlined]
 [4] materialize(::Base.Broadcast.Broadcasted{StaticArrays.StaticArrayStyle{1},Nothing,typeof(+),Tuple{Tuple{Int64,Int64},SArray{Tuple{2},Int64,1,2}}}) at ./broadcast.jl:724
 [5] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by mateuszbaran**
I think this looks more or less right.

### CODE REVIEW

File: src/broadcast.jl [hunk 1]
```diff
@@ -110,7 +111,7 @@ scalar_getindex(x::Tuple{<: Any}) = x[1]
     exprs = similar(indices, Expr)
     for (j, current_ind) ∈ enumerate(indices)
         exprs_vals = [
-            (!(a[i] <: AbstractArray) ? :(scalar_getindex(a[$i])) : :(a[$i][$(broadcasted_index(sizes[i], current_ind))]))
+            (!(a[i] <: AbstractArray || a[i] <: Tuple) ? :(scalar_getindex(a[$i])) : :(a[$i][$(broadcasted_index(sizes[i], current_ind))]))
```
Comment (c42f) [inline src/broadcast.jl]: I guess this means we should kill off the `scalar_getindex(x::Tuple)` further up? TBH I'm not sure why that was ever there.

Comment (mateuszbaran) [reply src/broadcast.jl]: We could, it looks like it was there to allow broadcasting with one-element tuples.

Comment (c42f) [reply src/broadcast.jl]: Ok, I think we should remove it for consistency, and add some tests to check that the functionality still works. AFAICT cases like

```julia
SA[1,2,3] .* (SA[1,0,0],)
```

used to work because of the `scalar_getindex` hack and your changes preserves that functionality while also allowing more things to work.

TBH the fact that we check `a[i] <: AbstractArray` makes me nervous and it seems like these problems will recur with other user-defined types (because we may not respect the `broadcastable` API? I'm not an expert on how this is set up though).

Regardless of that what you've got here is a definite improvement so we should go with it.

**Comment by c42f** [comment]
I went ahead and removed that version of `scalar_getindex` for consistency.  Also I added a test to check that the previous functionality enabled by that still works.

In the process I thought I could tighten the tests up a bit more. They now check:
* That single element tuple broadcast with SA still works
* That expected things are inferred
* That the return types of these broadcasts are precisely as expected

Also I tried out the new `SA` convenience constructor.

I pushed all that to your branch — hope that's ok!  Please have a look over it and see whether it makes sense. (And we'll let full CI run again to keep me honest :-) )

File: test/broadcast.jl [hunk 2]
```diff
@@ -213,4 +213,21 @@ end
...
+        @test @inferred((SA[10 20; 30 40]) .+ (1,2))     === SA{Int}[11 21; 32 42]
+
+        add_bc!(m, v) = m .+= v  # Helper function; @inferred gets confused by .+= syntax
+        @test @inferred(add_bc!(MVector((1,2,3)), (10, 20, 30)))   ::MVector{3,Int}   == SA[11, 22, 33]
+        @test @inferred(add_bc!(MMatrix(SA[10 20; 30 40]), (1,2))) ::MMatrix{2,2,Int} == SA[11 21; 32 42]
+
+        # Tuples of SA
+        @test SA[1,2,3] .* (SA[1,0],) === SVector{3,SVector{2,Int}}(((1,0), (2,0), (3,0)))
+        # Unfortunately this case of nested broadcasting is not inferred
+        @test_broken @inferred(SA[1,2,3] .* (SA[1,0],))
```
Comment (c42f) [inline test/broadcast.jl]: BTW, this case wasn't inferred before either, so we haven't made it worse in this PR.

File: src/broadcast.jl (hunk 1 above)
Comment (mateuszbaran) [reply src/broadcast.jl]: > TBH the fact that we check `a[i] <: AbstractArray` makes me nervous and it seems like these problems will recur with other user-defined types (because we may not respect the `broadcastable` API? I'm not an expert on how this is set up though).

Yes, it's a bad hack that will bite us in the future but as far as I understand the broadcast machinery (I'm not an expert though) this unrolled broadcasting can't be expected to work with arbitrary types participating in broadcasting anyway. A potentially better solution would be checking `Base.BroadcastStyle` of `a[i]` for `Style{Tuple}` and `AbstractArrayStyle`, so that could be done as well. But constructing `Base.BroadcastStyle` in a generated function doesn't sound like a great idea either. Or we could construct `Base.BroadcastStyle` in `Base.copy(B::Broadcasted{StaticArrayStyle{M}})`.

This can be improved gradually so we can make this a little bit better in this PR first.

**Comment by mateuszbaran** [comment]
> I pushed all that to your branch — hope that's ok! Please have a look over it and see whether it makes sense. (And we'll let full CI run again to keep me honest :-) )

That's great, thanks :slightly_smiling_face: . I'll look over your changes.

File: test/broadcast.jl (hunk 2 above)
Comment (mateuszbaran) [reply test/broadcast.jl]: This inference failure is weird. `Base.copy(B::Broadcasted{StaticArrayStyle{M}})` fails to inline and then its return type is not inferred. But `Cthulhu.jl` says everything's OK when I descend to that method of `copy`. There seems to be a problem outside `StaticArrays`.

**Comment by mateuszbaran** [comment]
> Please have a look over it and see whether it makes sense.

I think the code makes sense :+1: .

**Comment by c42f** [comment]
Great, merged!
