### PR TITLE
Alternate approach to fix #556

### LINKED ISSUE #556: Slicing with colon and range fails
This used to work
```
julia> using StaticArrays
julia> s = @SMatrix [1 2; 3 4];
julia> s[:, 1:1]
ERROR: MethodError: no method matching similar(::SArray{Tuple{2,2},Int64,2,4}, ::Type{Int64}, ::Tuple{Base.Slice{SOneTo{2}},Int64})
julia> s[:, [true, false]]
ERROR: MethodError: no method matching similar(::SArray{Tuple{2,2},Int64,2,4}, ::Type{Int64}, ::Tuple{Base.Slice{SOneTo{2}},Int64})
```

However `s[:, 1]` works. I guess #549 might be related.

### PR DESCRIPTION
**Pull request by mbauman**
This restructures the similar method table along the lines that I suggested in https://github.com/JuliaArrays/StaticArrays.jl/pull/568#discussion_r241561280. I also used a bit of internals magic to match how the Base `OneTo` operates -- this is a little fragile but I think it is a good way to replicate how `OneTo` works.

### CODE REVIEW

File: src/abstractarray.jl [hunk 1]
```diff
@@ -119,22 +120,19 @@ similar(::Type{A},::Type{T},s::Size{S}) where {A<:AbstractArray,T,S} = mutable_s
...
-# We should be able to deal with SOneTo axes
-similar(::A, shape::Tuple{SOneTo, Vararg{SOneTo}}) where {A<:AbstractArray} = similar(A, eltype(A), shape)
-similar(::Type{A}, shape::Tuple{SOneTo, Vararg{SOneTo}}) where {A<:AbstractArray} = similar(A, eltype(A), shape)
-
-similar(::A,::Type{T}, shape::Tuple{SOneTo, Vararg{SOneTo}}) where {A<:AbstractArray,T} = similar(A, T, Size(last.(shape)))
-similar(::Type{A},::Type{T}, shape::Tuple{SOneTo, Vararg{SOneTo}}) where {A<:AbstractArray,T} = similar(A, T, Size(last.(shape)))
+# Support tuples of mixtures of `SOneTo`s alongside the normal `Integer` and `OneTo` options
+# by simply converting them to either a tuple of Ints or a Size, re-dispatching to either one
+# of the above methods (in the case of Size) or a base fallback (in the case of Ints).
+const HeterogeneousShape = Union{Integer, Base.OneTo, SOneTo}
```
Comment (pablosanjose) [inline src/abstractarray.jl]: Are you sure you need Base.OneTo here? Base converts OneTo to Ints. Also, you can get IdentityUnitRange{<:SOneTo} here, shouldn't it be included in HeterogeneousShape? (This is what I did in #568)

File: src/abstractarray.jl [hunk 2]
```diff
@@ -119,22 +120,19 @@ similar(::Type{A},::Type{T},s::Size{S}) where {A<:AbstractArray,T,S} = mutable_s
...
+similar(::Type{A}, shape::Tuple{HeterogeneousShape, Vararg{HeterogeneousShape}}) where {A<:AbstractArray} = similar(A, homogenize_shape(shape))
+# Use an Array for StaticArrays if we don't have a statically-known size
+similar(::Type{A}, shape::Tuple{Int, Vararg{Int}}) where {A<:StaticArray} = Array{eltype(A)}(undef, shape)
 
-# Handle mixtures of SOneTo and other ranges (probably should make Base more robust here)
-similar(::Type{A}, shape::Tuple{AbstractUnitRange, Vararg{AbstractUnitRange}}) where {A<:AbstractArray} = similar(A, length.(shape)) # Jumps back to 2-argument form in Base
-similar(::Type{A},::Type{T}, shape::Tuple{AbstractUnitRange, Vararg{AbstractUnitRange}}) where {A<:AbstractArray,T} = similar(A, length.(shape))
+homogenize_shape(::Tuple{}) = ()
+homogenize_shape(shape::Tuple{Vararg{SOneTo}}) = Size(map(last, shape))
+homogenize_shape(shape::Tuple{Vararg{HeterogeneousShape}}) = map(last, shape)
```
Comment (pablosanjose) [inline src/abstractarray.jl]: Nice. I now see that we should *only* do the `static_similar` when *all* elements of `shape` are statically known (i.e. `s[:, 1:2]` should produce a `Matrix` not an `MMatrix`). However the static cases include `SOneTo` and also `IdentityUnitRange{<:SOneTo}`, that gets produced in base when you do `s[:,1:2]`, right?

File: src/abstractarray.jl [hunk 3]
```diff
@@ -119,22 +120,19 @@ similar(::Type{A},::Type{T},s::Size{S}) where {A<:AbstractArray,T,S} = mutable_s
...
 
-const SOneToLike{n} = Union{SOneTo{n}, Base.Slice{SOneTo{n}}}
-deslice(ax::SOneTo) = ax
-deslice(ax::Base.Slice) = ax.indices
-similar(::A,::Type{T}, shape::Tuple{SOneToLike, Vararg{SOneToLike}}) where {A<:AbstractArray,T} = similar(A, T, Size(last.(deslice.(shape))))
-similar(::Type{A},::Type{T}, shape::Tuple{SOneToLike, Vararg{SOneToLike}}) where {A<:AbstractArray,T} = similar(A, T, Size(last.(deslice.(shape))))
+similar(A::AbstractArray, ::Type{T}, shape::Tuple{HeterogeneousShape, Vararg{HeterogeneousShape}}) where {T} = similar(A, T, homogenize_shape(shape))
+similar(::Type{A}, shape::Tuple{HeterogeneousShape, Vararg{HeterogeneousShape}}) where {A<:AbstractArray} = similar(A, homogenize_shape(shape))
+# Use an Array for StaticArrays if we don't have a statically-known size
+similar(::Type{A}, shape::Tuple{Int, Vararg{Int}}) where {A<:StaticArray} = Array{eltype(A)}(undef, shape)
```
Comment (pablosanjose) [inline src/abstractarray.jl]: Is this one necessary? We have`similar(a::AbstractArray, ::Type{T}, dims::Dims{N}) where {T,N}    = Array{T,N}(undef, dims)` in base

File: src/abstractarray.jl (hunk 1 above)
Comment (pablosanjose) [reply src/abstractarray.jl]: Aaah,  I see what you've done here. You've overridden the `similar(a::AbstractArray{T}, dims::Tuple)` in base by including `Base.OneTo`. Sorry, carry on!

File: src/abstractarray.jl (hunk 2 above)
Comment (pablosanjose) [reply src/abstractarray.jl]: As above, your definition of `HeterogenousShape` skips the creation of `IdentityUnitRange`, please ignore this

File: src/abstractarray.jl (hunk 3 above)
Comment (pablosanjose) [reply src/abstractarray.jl]: (I can confirm that removing this definition doesn't make any test fail locally under v1.1)

Comment (mbauman) [reply src/abstractarray.jl]: Ah, yes, I hit a failure at the REPL at one point with a higher-level function, but I think it was due to an intermediate state of the other methods.

I'm not sure if there's any examples where a higher-level function would fail without this, but Base supports a `similar(T, (2,3))` API where `T` is the type of an AbstractArray.  It falls back to just calling `T(undef, (2, 3))`, which will of course fail for a `StaticArray`.  I can add a specific test for this line.

**Comment by pablosanjose** [comment]
I absolutely agree with the above. I realised this after doing some benchmarking of those kind of cases. The `MArray` version resulted in  microsecond runtimes (dynamic dispatch, I assume), while returning an `Array` was 30-60 ns, the typical times for such things. So I think your solution is the correct one. Thanks!

**Comment by JeffBezanson** [comment]
Bump. Can this be merged?

**Comment by pablosanjose** [comment]
+1 to merge

**Comment by c42f** [comment]
Sorry for the delay, this is one of those odd occasions where the author of the PR is more qualified to comment on its validity than most of the maintainers. Or certainly than myself ;-)

From what I can see quickly this looks completely reasonable, I'll fix the conflict, rerun CI and merge if it passes. I assume people will also want a new release including this fix.
