### PR TITLE
Minimalist logdet performance fix for large matrices

### LINKED ISSUE #267: Calling log(det()) instead of logdet()
#262 introduces the regression that StaticArrays' ``logdet`` just calling ``log`` after ``det`` instead of the specialized ``logdet`` in Base.

### PR DESCRIPTION
**Pull request by andyferris**
Minimalist version of #268. (Sorry Chris - we can do some size traits separately if we want, but may as well fix this quickly-er)

Fixes #267.

### CODE REVIEW

File: src/det.jl [hunk 1]
```diff
@@ -39,3 +37,7 @@ end
 @inline function _det(::Size, A::StaticMatrix)
     return det(Matrix(A))
 end
+
+@inline logdet(a::StaticMatrix) = _logdet(Size(a), a)
+@inline _logdet(::Union{Size{(1,1)}, Size{(2,2)}, Size{(3,3)}}, a::StaticMatrix) = log(det(a))
+@inline _logdet(::Size, a::StaticMatrix) = logdet(drop_sdims(a))
```
Comment (mschauer) [inline src/det.jl]: Do we drop or drop and reattach fixed dimensions in such cases?

**Comment by andyferris** [comment]
Feel free to tag @mschauer if you feel like it (I'm going to bed :) )

**Comment by c42f** [comment]
No problems at all.  I've just been working on other packages (MicroLogging, FastClosures)... no time for StaticArrays for the past month :-/

I like what you've got here, it's simple.
