### PR TITLE
Fix `exp` of `SMatrix` with large entries #1295

### LINKED ISSUE #1295: [BUG] `exp` of `SMatrix` fails numerically
MWE:

```julia
julia> using StaticArrays

julia> M = 800.0 * [-1 1; 1 -1]
2×2 Matrix{Float64}:
 -800.0   800.0
  800.0  -800.0

julia> exp(M)
2×2 Matrix{Float64}:
 0.5  0.5
 0.5  0.5

julia> S = SMatrix{2,2}(M)
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 -800.0   800.0
  800.0  -800.0

julia> exp(S)
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 NaN  NaN
 NaN  NaN
```

### PR DESCRIPTION
**Pull request by juliohm**
Fix #1295 

Appreciate if you can review this @mikmoore.

### CODE REVIEW

**Comment by juliohm** [comment]
Tests are failing on Julia nightly for unrelated reasons.

Appreciate it if you could review the hotfix.

File: src/expm.jl [hunk 1]
```diff
@@ -25,25 +26,50 @@ end
...
+        δ = sqrt(v) / 2
+        e₊ = exp(m + δ)
+        e₋ = exp(m - δ)
+        e₁ = e₊ + e₋
+        e₂ = e₊ - e₋
+        c₂ = (a - d) / 2δ
+        m11 = (e₁ + c₂ * e₂) / 2
+        m12 = (b / δ) * e₂ / 2
+        m21 = (c / δ) * e₂ / 2
+        m22 = (e₁ - c₂ * e₂) / 2
```
Comment (mikmoore) [inline src/expm.jl:53]:
```suggestion
        e₊ = exp(m + δ) / 2
        e₋ = exp(m - δ) / 2
        e₁ = e₊ + e₋
        e₂ = e₊ - e₋
        c₂ = (a - d) / 2δ
        m11 = e₁ + c₂ * e₂
        m12 = (b / δ) * e₂
        m21 = (c / δ) * e₂
        m22 = e₁ - c₂ * e₂
```
Looks like this might save a couple multiplies, but really it was fine the way it was too.

**Review by mikmoore — APPROVED** [review]
Looks good to me. Thanks for the detailed comments!

File: src/expm.jl [hunk 2]
```diff
@@ -25,25 +26,50 @@ end
...
-        z1 = cosh(z / 2)
-        z2 = sinh(z / 2) / z
+        # In this case the formulas in the entries of the matrix
+        # are a function of cosh and sinh, and could (in theory)
+        # follow the same code pattern of the other branches (v ≤ 0).
+        # However, cosh and sinh explode with large arguments and
+        # we use the following identity to avoid numerical issues:
+        #
+        # exp(m) * [c₁ * cohs(δ) + c₂ * sinh(δ)] =
+        #   c₁ * (e₊ + e₋) / 2 + c₂ * (e₊ - e₋) / 2
```
Comment (mikmoore) [inline src/expm.jl:39]: If you move the `/2`'s as considered below, I guess this comment could be updated to move them as well.

File: src/expm.jl (hunk 1 above)
Comment (juliohm) [reply src/expm.jl:53]: Thank you @mikmoore , I will update the code accordingly.

**Comment by juliohm** [comment]
Someone needs to run the workflows again.

**Comment by juliohm** [comment]
This is ready to merge. Could someone please release a patch with this hotfix?

**Comment by juliohm** [comment]
Done 👍🏽
