### PR TITLE
Fix eltype in empty static array construction

### LINKED ISSUE #651: Type Stability of Constructor
There are some type stability issues (at least for StaticArrays v0.11.0) for an empty `SVector`:
```julia
julia> using StaticArrays

julia> SVector{0, Float64}([])
0-element SArray{Tuple{0},Any,1,0} with indices SOneTo(0)

julia> SVector{0, Float64}(Float64[])
0-element SArray{Tuple{0},Float64,1,0} with indices SOneTo(0)

julia> SVector{0, Float64}(Float32[])
0-element SArray{Tuple{0},Float32,1,0} with indices SOneTo(0)
```
I expected to get a `0-element SArray{Tuple{0},Float64,1,0} with indices SOneTo(0)` in all three cases, similar to the non-empty case:
```julia
julia> SVector{1, Float64}([2])
1-element SArray{Tuple{1},Float64,1,1} with indices SOneTo(1):
 2.0

julia> SVector{1, Float64}(Float64[2])
1-element SArray{Tuple{1},Float64,1,1} with indices SOneTo(1):                      
 2.0                                                                                
                                                                                    
julia> SVector{1, Float64}(Float32[2])
1-element SArray{Tuple{1},Float64,1,1} with indices SOneTo(1):                      
 2.0                                                                                
```

This must have worked at some point in the past, since I got errors caused by this recently on Travis for one of my packages (see https://travis-ci.org/ranocha/SummationByPartsOperators.jl/builds/575385284). The last build before (where everything was fine) has been on 2019-03-07.

### PR DESCRIPTION
**Pull request by c42f**
Fixes #651

### CODE REVIEW

File: src/convert.jl [hunk 1]
```diff
@@ -26,7 +26,8 @@ end
     return _convert(SA, a, Length(SA))
 end
 
-@inline _convert(SA, a, ::Length{L}) where L = SA(unroll_tuple(a, Length(SA)))
+@inline _convert(SA, a, l::Length) = SA(unroll_tuple(a, l))
+@inline _convert(SA::Type{<:StaticArray{<:Tuple,T}}, a, ::Length{0}) where T = similar_type(SA, T)(())
```
Comment (andyferris) [inline src/convert.jl]: I suspect a type assertion would be good here (that the output is indeeed an `SA`).

Comment (c42f) [reply src/convert.jl]: We could do that. Which error condition are you trying to cover, is it protection for the user to avoid stack overflows when they have a broken `similar_type` (constructor calling `_convert` calling constructor etc) or some such?

Comment (andyferris) [reply src/convert.jl]: Just guarding against the case that `similar_type(SA)` isn’t an `SA` (like rotations) which means constructors and conversion might return a rather surprising result.
