### PR TITLE
Define logabsdet(::SMatrix), det & friends for LU

### LINKED ISSUE #489: logabsdet(::SMatrix) fails
```julia
julia> VERSION # (this is `master`, but the same happens on 1.0)
v"1.1.0-DEV.199"

julia> using LinearAlgebra, StaticArrays

julia> mx = SMatrix{2,2}(Float64.(1:4)...)
2×2 SArray{Tuple{2,2},Float64,2,4}:
 1.0  3.0
 2.0  4.0

julia> logabsdet(mx)
ERROR: MethodError: no method matching lu!(::SArray{Tuple{2,2},Float64,2,4}, ::Val{true}; check=false)
```

### PR DESCRIPTION
**Pull request by tpapp**
1. define a `logabsdet` for `SMatrix`, fixes #489

2. define methods for `det`, `logdet`, `logabsdet` for LU (cf `LinearAlgebra`, which has these methods)

3. make `det`, `logdet`, `logabsdet` fall back to using the LU methods (to avoid code repetition)

4. include `lu.jl` first, since `det.jl` uses code from it

5. incidental consistency fixes

### CODE REVIEW

File: src/det.jl [hunk 1]
```diff
@@ -42,13 +42,24 @@ end
...
 
+det(F::LU) = det(F.U) * _parity(F.p)
+
+function logdet(F::LU)
+    d, s = logabsdet(F.U)
+    d + log(s * _parity(F.p))
+end
+
+function logabsdet(F::LU)
+    d, s = logabsdet(F.U)
```
Comment (andyferris) [inline src/det.jl:53]: What does this dispatch to?

Comment (tpapp) [reply src/det.jl:53]: Good catch! It does to the default method in `LinearAlgebra` (like it did before). However, this is an opportunity for improvement, so I will do something nicer.

**Comment by tpapp** [comment]
Friendly bump: it would be great if someone could review this. I am happy to make any changes necessary.

File: src/det.jl [hunk 2]
```diff
@@ -44,6 +44,13 @@ end
 
 det(F::LU) = det(F.U) * _parity(F.p)
 
+function logabsdet(A::Union{LowerTriangular{<:Any,<:StaticMatrix},
+                            UpperTriangular{<:Any,<:StaticMatrix}})
+    checksquare(A)
```
Comment (andyferris) [inline src/det.jl:49]: My recollection from years ago (yikes!) is that this method is slow. Have you checked if it is ellided? We can do it statically in a variety of ways, the simplest of which would be to add type parameter constraints like `<:StaticMatrix{S,S} where S`

Comment (tpapp) [reply src/det.jl:49]: According to `@code_warntype`, it is fully elided.

In any case, it is used in multiple places in the package.

**Comment by tpapp** [comment]
Thanks for thinking about these points, I will try to address these in turn.

1. According to `@code_warntype`, `checksquare` is elided.

2. Not sure what benchmarks you would prefer here, since this method errored before. If I compare to doing `logabsdet(A::SMatrix)` vs making it a `Matrix`, the static version is 3-10x faster, depending on matrix size. But note that LU dominates all calculations, so this is really a benchmark of that.

3. `Complex` matrices work with `logabsdet`. `Hermitian` unfortunately doesn't, but it didn't before this PR for `det` either. I would prefer if those things were addressed in another PR. Same applies to better algorithms for `Symmetric`. I can open an issue for these if you prefer.

Unless there are further suggestions, I would really appreciate if this PR could get merged. I am happy to contribute to this package but I like to do it in small pieces, each improving some functionality.

**Comment by andyferris** [comment]
Alright - thanks for that @tpapp!

I agree, small pieces are definitely better :)

**Comment by andyferris** [comment]
Is this or something else causing the latest test failure on master?

https://github.com/JuliaArrays/StaticArrays.jl/actions/runs/89972783

**Comment by tpapp** [comment]
The errors in the log look like
```julia
matrix multiply-add: Test Failed at /home/runner/work/StaticArrays.jl/StaticArrays.jl/test/matrix_multiply_add.jl:9
  Expression: #= /home/runner/work/StaticArrays.jl/StaticArrays.jl/test/matrix_multiply_add.jl:9 =# @allocated(mul!(c, A, b)) == 0
   Evaluated: 12 == 0
Stacktrace:
 [1] test_multiply_add(::Int32, ::Int32, ::Type{T} where T) at /home/runner/work/StaticArrays.jl/StaticArrays.jl/test/matrix_multiply_add.jl:9
 [2] top-level scope at /home/runner/work/StaticArrays.jl/StaticArrays.jl/test/matrix_multiply_add.jl:175
 [3] top-level scope at /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1114
 [4] top-level scope at /home/runner/work/StaticArrays.jl/StaticArrays.jl/test/matrix_multiply_add.jl:172
matrix multiply-add: Test Failed at /home/runner/work/StaticArrays.jl/StaticArrays.jl/test/matrix_multiply_add.jl:9
  Expression: #= /home/runner/work/StaticArrays.jl/StaticArrays.jl/test/matrix_multiply_add.jl:9 =# @allocated(mul!(c, A, b)) == 0
   Evaluated: 12 == 0
```
so I do not think it is related. However, if you find that is, just ping me and I am happy to contribute a fix quickly.

**Comment by c42f** [comment]
I suspect those test failures may be due to (1) the unreliability of `@allocated` in 1.4+, and (2) compiler changes in Julia master (though who knows exactly what... may be the inline-allocation changes which just landed in time for 1.4... they'd presumably have a big impact on codegen).

So yes, nothing to do with the code here.

**Comment by c42f** [comment]
Attempted quick fix for CI: https://github.com/JuliaArrays/StaticArrays.jl/pull/776
